# Generated by Django 6.0 on 2026-02-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='imgURL',
            field=models.CharField(default='https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExeHNoZGl1azZ0dm9razJxbnBjNnd3bXc5Y2V2cmxvajl0bHkyYTV1cSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/v6aOjy0Qo1fIA/giphy.gif', max_length=256),
        ),
    ]
