# Generated by Django 6.0 on 2026-02-12 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=False, max_length=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='activeUntil',
            field=models.DateTimeField(blank=True, default=datetime.date(2026, 2, 12), max_length=20),
        ),
    ]
