# Generated by Django 6.0 on 2026-02-15 06:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_active_listing_activeuntil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
        migrations.AlterField(
            model_name='listing',
            name='activeUntil',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, max_length=20),
        ),
    ]
