# Generated by Django 6.0 on 2026-02-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_listing_active_alter_listing_activeuntil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Technology', 'tech'), ('Gay', 'gay'), ('Duck', 'duck'), ('None', 'none')], default='None', max_length=20),
        ),
    ]
