# Generated by Django 6.0 on 2026-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_discription_listing_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('fay', 'gay'), ('duck', 'duck'), ('none', 'none')], default='None', max_length=20),
        ),
    ]
